org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# Variables de compilacion de Flutter para ejecuciones iniciadas directamente
# desde el modulo Android. Cada valor es Base64 y la lista usa comas.
# API_HOST=192.168.0.140
# dart-defines=QVBJX0hPU1Q9MTkyLjE2OC4wLjE0MA==

# API_HOST=192.168.1.11
#dart-defines=QVBJX0hPU1Q9MTkyLjE2OC4xLjEx

# Servidor Docker de producción en la red local.
# API_HOST=192.168.1.4, API_PUERTO=80
dart-defines=QVBJX0hPU1Q9MTkyLjE2OC4xLjQ=,QVBJX1BVRVJUTz04MA==
